/*
 This file is part of pspsharp.

 pspsharp is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 pspsharp is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with pspsharp.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace pspsharp.Debugger.DisassemblerModule
{
	using Constants = pspsharp.util.Constants;
	using JpcspDialogManager = pspsharp.util.JpcspDialogManager;

	public class DumpCodeDialog : javax.swing.JDialog
	{

		public const int DUMPCODE_APPROVE = 1;
		internal int retVal = 0;

		public DumpCodeDialog(java.awt.Frame parent, int start) : base(parent, true)
		{
			initComponents();
			LocationRelativeTo = parent;
			txtStartAddress.Text = string.Format("0x{0:X8}", start);
			txtEndAddress.Text = string.Format("0x{0:X8}", start);
		}

		public virtual int StartAddress
		{
			get
			{
				return Integer.decode(txtStartAddress.Text);
			}
		}

		public virtual int EndAddress
		{
			get
			{
				return Integer.decode(txtEndAddress.Text);
			}
		}

		public virtual string Filename
		{
			get
			{
				return txtFilename.Text;
			}
		}

		public virtual int ReturnValue
		{
			get
			{
				return retVal;
			}
		}

		private class AddressInputVerifier : InputVerifier
		{
			private readonly DumpCodeDialog outerInstance;

			public AddressInputVerifier(DumpCodeDialog outerInstance)
			{
				this.outerInstance = outerInstance;
			}


			public override bool verify(JComponent input)
			{
				try
				{
					JTextField tf = (JTextField) input;
					int value = Integer.decode(tf.Text);

					// code always starts at DWORD address
					if ((value % 4) != 0)
					{
						value /= 4;
					}

					tf.Text = string.Format("0x{0:X8}", value);
					return true;
				}
				catch (System.FormatException)
				{
					return false;
				}
			}
		}

		/// <summary>
		/// This method is called from within the constructor to initialize the form.
		/// WARNING: Do NOT modify this code. The content of this method is always
		/// regenerated by the Form Editor.
		/// </summary>
//JAVA TO C# CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
//ORIGINAL LINE: @SuppressWarnings("unchecked") private void initComponents()
		private void initComponents()
		{

			lblStartAddress = new javax.swing.JLabel();
			txtStartAddress = new JTextField();
			lblEndAddress = new javax.swing.JLabel();
			lblFilename = new javax.swing.JLabel();
			txtEndAddress = new JTextField();
			txtFilename = new JTextField();
			btnFilename = new javax.swing.JButton();
			btnOk = new javax.swing.JButton();
			btnCancel = new pspsharp.GUI.CancelButton();

			DefaultCloseOperation = javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
			java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pspsharp/languages/pspsharp"); // NOI18N
			Title = bundle.getString("DumpCodeDialog.title"); // NOI18N
			Resizable = false;

			lblStartAddress.Text = bundle.getString("DumpCodeDialog.lblStartAddress.text"); // NOI18N

			txtStartAddress.Font = new java.awt.Font("Courier New", 0, 12); // NOI18N
			txtStartAddress.HorizontalAlignment = JTextField.CENTER;
			txtStartAddress.Text = "0x00000000"; // NOI18N
			txtStartAddress.InputVerifier = new AddressInputVerifier(this);

			lblEndAddress.Text = bundle.getString("DumpCodeDialog.lblEndAddress.text"); // NOI18N

			lblFilename.Text = bundle.getString("DumpCodeDialog.lblFilename.text"); // NOI18N

			txtEndAddress.Font = new java.awt.Font("Courier New", 0, 12); // NOI18N
			txtEndAddress.HorizontalAlignment = JTextField.CENTER;
			txtEndAddress.Text = "0x00000000"; // NOI18N
			txtEndAddress.InputVerifier = new AddressInputVerifier(this);

			txtFilename.Editable = false;
			txtFilename.Text = "dump.txt"; // NOI18N

			btnFilename.Text = "..."; // NOI18N
			btnFilename.PreferredSize = new java.awt.Dimension(25, 25);
			btnFilename.addActionListener(new ActionListenerAnonymousInnerClass(this));

			btnOk.Text = bundle.getString("OkButton.text"); // NOI18N
			btnOk.addActionListener(new ActionListenerAnonymousInnerClass2(this));

			btnCancel.Text = bundle.getString("CancelButton.text"); // NOI18N
			btnCancel.Parent = this;

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(ContentPane);
			ContentPane.Layout = layout;
			layout.HorizontalGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblStartAddress).addComponent(lblEndAddress).addComponent(lblFilename)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtStartAddress).addComponent(txtEndAddress).addGroup(layout.createSequentialGroup().addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, short.MaxValue).addComponent(btnFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))).addGroup(layout.createSequentialGroup().addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, short.MaxValue).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, short.MaxValue))).addContainerGap());
			layout.VerticalGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblStartAddress).addComponent(txtStartAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblEndAddress).addComponent(txtEndAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblFilename)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnOk).addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap());

			pack();
		} // </editor-fold>//GEN-END:initComponents

		private class ActionListenerAnonymousInnerClass : java.awt.@event.ActionListener
		{
			private readonly DumpCodeDialog outerInstance;

			public ActionListenerAnonymousInnerClass(DumpCodeDialog outerInstance)
			{
				this.outerInstance = outerInstance;
			}

			public void actionPerformed(java.awt.@event.ActionEvent evt)
			{
				outerInstance.btnFilenameActionPerformed(evt);
			}
		}

		private class ActionListenerAnonymousInnerClass2 : java.awt.@event.ActionListener
		{
			private readonly DumpCodeDialog outerInstance;

			public ActionListenerAnonymousInnerClass2(DumpCodeDialog outerInstance)
			{
				this.outerInstance = outerInstance;
			}

			public void actionPerformed(java.awt.@event.ActionEvent evt)
			{
				outerInstance.btnOkActionPerformed(evt);
			}
		}

		private void btnFilenameActionPerformed(java.awt.@event.ActionEvent evt)
		{ //GEN-FIRST:event_btnFilenameActionPerformed
			JFileChooser fc = new JFileChooser();
			fc.DialogTitle = java.util.ResourceBundle.getBundle("pspsharp/languages/pspsharp").getString("DumpCodeDialog.dlgOutputFile.title");

			fc.SelectedFile = new File(txtFilename.Text);
			fc.addChoosableFileFilter(Constants.fltTextFiles);
			fc.FileFilter = Constants.fltTextFiles;

			int returnVal = fc.showOpenDialog(this);
			if (returnVal != JFileChooser.APPROVE_OPTION)
			{
				return;
			}

			txtFilename.Text = fc.SelectedFile.AbsolutePath;
		} //GEN-LAST:event_btnFilenameActionPerformed

		private void btnOkActionPerformed(java.awt.@event.ActionEvent evt)
		{ //GEN-FIRST:event_btnOkActionPerformed
			if (StartAddress > EndAddress)
			{
				JpcspDialogManager.showError(this, java.util.ResourceBundle.getBundle("pspsharp/languages/pspsharp").getString("DumpCodeDialog.strErrAddressRange.title"));
				return;
			}

			retVal = DUMPCODE_APPROVE;
			Visible = false;
		} //GEN-LAST:event_btnOkActionPerformed
		// Variables declaration - do not modify//GEN-BEGIN:variables
		private pspsharp.GUI.CancelButton btnCancel;
		private javax.swing.JButton btnFilename;
		private javax.swing.JButton btnOk;
		private javax.swing.JLabel lblEndAddress;
		private javax.swing.JLabel lblFilename;
		private javax.swing.JLabel lblStartAddress;
		private JTextField txtEndAddress;
		private JTextField txtFilename;
		private JTextField txtStartAddress;
		// End of variables declaration//GEN-END:variables
	}

}